# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [1]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [6]:
data = pd.read_csv('/content/wind_stats.tsv', sep = "\s+", parse_dates = [[0,1,2]])
data.head()

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-879358548.py:1: SyntaxWarning: invalid escape sequence '\s'
  data = pd.read_csv('/content/wind_stats.tsv', sep = "\s+", parse_dates = [[0,1,2]])
/tmp/ipython-input-879358548.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  data = pd.read_csv('/content/wind_stats.tsv', sep = "\s+", parse_dates = [[0,1,2]])
/tmp/ipython-input-879358548.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data = pd.read_csv('/content/wind_stats.tsv', sep = "\s+", parse_dates = [[0,1,2]])

,Yr_Mo_Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   datetime64[ns]
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: datetime64[ns](1), float64(12)
memory usage: 667.8 KB

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [9]:
data["Yr_Mo_Dy"] = pd.to_datetime(data["Yr_Mo_Dy"])
data = data.set_index('Yr_Mo_Dy')
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
2061-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
2061-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2061-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
2061-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
2061-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [10]:
count = data.isnull().sum()
count

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [11]:
non_missing = data.notnull().sum()
non_missing

RPT    6568
VAL    6571
ROS    6572
KIL    6569
SHA    6572
BIR    6574
DUB    6571
CLA    6572
MUL    6571
CLO    6573
BEL    6574
MAL    6570
dtype: int64

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [12]:
count.sum() / data.notna().sum().sum()

np.float64(0.0003931166541968373)

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days

#### A different set of numbers for each location.

In [17]:
loc_stats = data.describe()
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [16]:
day_stats = data.agg(['min', 'max', 'mean', 'std'], axis=1)
day_stats

             min    max       mean       std
Yr_Mo_Dy
2061-01-01  9.29  18.50  13.018182  2.808875
2061-01-02  6.50  17.54  11.336364  3.188994
2061-01-03  6.17  18.50  11.641818  3.681912
2061-01-04  1.79  11.75   6.619167  3.198126
2061-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [18]:
avg_jan = data[data.index.month == 1].mean()
avg_jan

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [19]:
data.groupby(data.index.to_period('A')).mean()

/tmp/ipython-input-517584096.py:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'Y' instead.
  data.groupby(data.index.to_period('A')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370
2061,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
2062,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
2063,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
2064,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
2065,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
2066,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
2067,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
2068,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
2069,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
2070,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
2071,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
2072,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
2073,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
2074,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671

### Step 13. Downsample the record to a monthly frequency for each location.

In [20]:
data.groupby(data.index.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1975-01,17.100323,15.812903,13.942581,8.081935,13.934194,8.437742,13.179677,12.601935,13.000645,11.064839,19.266774,21.713226
1975-02,12.889643,13.217143,11.428929,5.181786,10.488214,6.391786,7.433214,8.679643,8.996429,6.187143,12.937143,13.868214
1975-03,12.605806,10.093226,13.265806,5.503226,8.548065,5.595484,9.509677,7.425806,8.756452,8.203226,11.386452,15.523226
1975-04,12.491333,10.339333,11.535333,5.969333,9.285667,6.202333,8.556333,8.033333,9.574667,8.724333,12.909667,15.134333
1975-05,9.911613,7.307419,13.805161,4.450645,7.537742,4.507097,6.039355,6.365484,6.742903,5.934839,11.259032,11.527742
...,...,...,...,...,...,...,...,...,...,...,...,...
2074-08,10.369032,10.131613,10.715484,4.638710,8.674839,5.689677,7.324194,8.739032,7.875806,7.217419,12.354194,14.571290
2074-09,14.830667,12.813333,12.155667,6.036667,10.863333,6.724000,9.063333,8.909333,8.410667,7.249333,12.320333,16.237333
2074-10,14.282581,10.514839,11.642258,6.308387,9.713548,5.682581,10.829355,8.562258,7.775161,7.481935,13.368065,19.197742
2074-11,13.125333,12.139000,11.990333,6.086333,11.435333,6.299000,11.766667,9.329333,9.640333,8.216667,12.064000,17.919667
2074-12,18.511290,17.805806,14.773871,9.734839,16.944194,10.153871,16.602903,15.034194,14.883548,12.915161,18.803548,24.124194

### Step 14. Downsample the record to a weekly frequency for each location.

In [21]:
data.groupby(data.index.to_period('W')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1974-12-30/1975-01-05,10.008000,9.776000,9.852000,4.150000,10.576000,5.964000,12.926000,10.626000,11.510000,9.826000,15.052000,22.036000
1975-01-06/1975-01-12,17.101429,15.761429,14.434286,8.660000,14.552857,8.774286,14.272857,13.125714,13.602857,11.112857,20.184286,20.041429
1975-01-13/1975-01-19,17.617143,14.408571,15.210000,8.650000,12.952857,7.791429,11.325714,11.361429,12.065714,10.487143,17.114286,18.362857
1975-01-20/1975-01-26,20.720000,19.911429,15.350000,9.855714,16.964286,10.528571,15.137143,14.594286,14.935714,13.192857,23.338571,26.075714
1975-01-27/1975-02-02,16.637143,18.524286,12.712857,7.400000,13.052857,7.780000,10.404286,12.518571,11.742857,9.695714,19.915714,20.115714
...,...,...,...,...,...,...,...,...,...,...,...,...
2074-12-03/2074-12-09,14.631429,15.718571,11.297143,7.881429,16.415714,9.062857,16.612857,13.921429,14.148571,12.148571,19.205714,24.432857
2074-12-10/2074-12-16,17.887143,17.220000,12.930000,10.122857,17.125714,9.617143,15.845714,14.832857,13.608571,11.934286,17.987143,23.811429
2074-12-17/2074-12-23,23.152857,20.792857,18.422857,12.298571,18.087143,11.978571,18.202857,18.051429,17.118571,16.022857,22.338571,27.322857
2074-12-24/2074-12-30,19.938571,18.582857,16.461429,9.761429,17.725714,10.607143,17.188571,14.238571,15.435714,11.911429,16.181429,22.452857
2074-12-31/2075-01-06,16.040000,16.290000,15.210000,8.420000,13.670000,9.750000,15.250000,16.130000,15.040000,13.460000,18.540000,18.460000

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [22]:
weekly_stats = data.resample('W').agg(['min', 'max', 'mean', 'std'])
first_52_weeks = weekly_stats.head(52)
first_52_weeks

              RPT                                VAL                    \
              min    max       mean       std    min    max       mean
Yr_Mo_Dy
1975-01-05   5.37  14.04  10.008000  3.253655   5.63  13.54   9.776000
1975-01-12  10.71  22.13  17.101429  4.765223  10.79  21.09  15.761429
1975-01-19   8.00  33.12  17.617143  8.712091   8.00  25.58  14.408571
1975-01-26  16.25  26.50  20.720000  3.129238  14.37  29.50  19.911429
1975-02-02  11.96  21.09  16.637143  3.339105  13.67  21.46  18.524286
1975-02-09  10.75  19.00  14.034286  2.856845   7.12  17.79  12.867143
1975-02-16   7.46  14.42  12.162857  2.839447   6.04  17.54  11.507143
1975-02-23   3.71  17.46  11.437143  4.769919   3.08  17.62  10.124286
1975-03-02  11.21  18.08  13.924286  2.845282  11.42  21.29  16.078571
1975-03-09   4.33  17.04  10.254286  5.009827   5.04  14.71   9.511429
1975-03-16   9.00  18.84  12.555714  3.403688   5.00  13.92   9.095714
1975-03-23  10.71  16.54  13.720000  2.399111   6.63  14.46  10.328571
1975-03-30   8.50  17.16  13.974286  3.548055   6.29  16.96  10.947143
1975-04-06   9.92  17.50  13.838571  2.635150   7.33  15.12  10.677143
1975-04-13   6.96  21.84  15.484286  4.947076   3.33  17.12  11.217143
1975-04-20   7.41  19.62  12.944286  4.757881   9.13  16.04  12.631429
1975-04-27   4.25  10.46   6.902857  2.442476   1.42   9.62   5.154286
1975-05-04   1.63  22.54  12.602857  7.117190   3.96  16.50  11.500000
1975-05-11   6.13  17.92  12.672857  4.366554   4.21  15.41  10.131429
1975-05-18   6.21  13.54   8.064286  2.749472   2.83  10.04   6.387143
1975-05-25   4.38  11.75   8.025714  2.418118   2.50   9.59   5.150000
1975-06-01   6.92  12.83  10.285714  1.990702   4.42   8.79   6.627143
1975-06-08   6.63  23.21  11.772857  5.469085   4.92  18.38  12.460000
1975-06-15   3.96  13.33   9.005714  3.003852   1.96  10.58   6.225714
1975-06-22   5.41  15.37   9.694286  4.294259   1.79  15.21   7.691429
1975-06-29   6.17  11.38   9.221429  1.806225   4.71   9.71   7.422857
1975-07-06   4.96  10.83   8.094286  2.094014   3.21   8.00   4.757143
1975-07-13   7.83  14.33  11.492857  2.237727   6.83  12.71   8.167143
1975-07-20   1.71  15.41   9.964286  4.784955   3.63  12.58   9.327143
1975-07-27   4.17  18.88  11.648571  5.886497   2.83  16.29  10.432857
1975-08-03   5.83   9.21   7.594286  1.271572   1.08  10.41   5.825714
1975-08-10   8.08  17.83  11.417143  3.721240   3.29  15.75   8.838571
1975-08-17   3.67  11.92   7.108571  2.554365   4.38   7.87   6.118571
1975-08-24   4.92  14.67  10.620000  4.083287   4.17  13.50   8.601429
1975-08-31   3.13  17.50   7.962857  5.333197   2.75   9.71   5.797143
1975-09-07   5.96   9.17   7.415714  1.285365   2.71   7.83   5.857143
1975-09-14  10.25  20.50  14.564286  3.916167   8.83  16.92  11.680000
1975-09-21   5.63  14.37  10.000000  2.806267   3.88  17.08   8.840000
1975-09-28  11.50  23.54  17.594286  5.006725   6.71  20.91  14.617143
1975-10-05  13.17  19.79  15.648571  2.764709  11.04  17.00  13.654286
1975-10-12   3.25  12.08   6.494286  3.025078   3.21  12.12   6.045714
1975-10-19   4.21  17.79  12.712857  4.921161   5.13  22.46  13.095714
1975-10-26  13.75  27.42  19.560000  5.019196  16.42  25.84  20.808571
1975-11-02  10.75  19.92  14.774286  2.921808  10.34  18.79  15.417143
1975-11-09   3.33  17.92  10.178571  4.384060   2.46  13.79   8.501429
1975-11-16   6.46  27.63  13.322857  7.282229   4.96  20.25  11.315714
1975-11-23   2.67  22.75  13.005714  6.439487   2.17  19.12  10.220000
1975-11-30   6.38  19.00  11.567143  4.432816   4.63  18.41  11.037143
1975-12-07   7.38  26.96  13.371429  7.604756   3.58  22.08   9.885714
1975-12-14   2.21  20.00   8.624286  6.170823   1.54  16.75   5.720000
1975-12-21   3.37  16.17   9.207143  3.911056   0.54  13.33   4.921429
1975-12-28   8.38  18.71  13.674286  3.596539   5.29  15.04  12.015714

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
Yr_Mo_Dy                            ...
1975-01-05  3.693634   7.29  12.17  ...   9.826000  3.655185   7.71  22.13
1975-01-12  3.805923   8.75  19.00  ...  11.112857  3.649679  11.46  27.33
1975-01-19  6.660872   6.54  25.88  ...  10.487143  6.219345  10.13  28.71
1975-01-26  5.511622  12.50  21.29  ...  13.192857  3.914199  16.58  32.30
1975-02-02  2.531665   8.87  17.96  ...   9.695714  3.555085  13.59  26.92
1975-02-09  3.636705   8.12  15.92  ...   5.797143  1.593348   7.41  16.46
1975-02-16  4.407629   7.33  16.96  ...   4.991429  4.268522   3.75  19.25
1975-02-23  5.270692   4.33  16.17  ...   6.781429  4.874011   5.79  21.00
1975-03-02  3.695445   9.13  15.83  ...   6.035714  1.558245   8.04  15.50
1975-03-09  4.389003   5.66  14.00  ...   7.030000  4.624060   5.50  19.70
1975-03-16  3.636408  12.17  28.33  ...   8.674286  3.664978   4.12  16.92
1975-03-23  2.708077   9.59  20.54  ...   8.130000  2.521461   7.46  14.88
1975-03-30  3.658537   8.75  17.79  ...   9.761429  1.651842   9.04  18.05
1975-04-06  2.614866   8.29  18.34  ...   9.521429  3.489563   8.04  17.41
1975-04-13  4.891992   6.79  17.00  ...  12.142857  4.382243   9.59  20.91
1975-04-20  2.491087   5.46  17.71  ...   7.327143  1.769084   8.38  19.87
1975-04-27  2.937561   3.29  13.50  ...   4.810000  2.137896   4.17   9.62
1975-05-04  4.970101   4.92  17.16  ...   7.934286  4.881990   3.83  19.33
1975-05-11  3.584329   9.17  27.67  ...   8.185714  3.836143   7.83  15.41
1975-05-18  2.598081   3.46  22.17  ...   4.135714  2.222078   4.33  14.50
1975-05-25  2.444054   3.04  16.66  ...   6.367143  2.458846   9.08  15.75
1975-06-01  1.576903   7.92  24.54  ...   5.868571  2.386884   9.38  19.08
1975-06-08  4.894054   2.92  18.79  ...   9.742857  5.298165   6.29  20.25
1975-06-15  3.163963   2.88   8.92  ...   4.900000  3.096746   5.75  13.08
1975-06-22  5.072466   6.13  16.13  ...   6.238571  3.896141   5.00  21.50
1975-06-29  2.105403   5.71  17.00  ...   4.582857  2.188452   5.21  13.33
1975-07-06  1.606297   3.50   9.96  ...   3.077143  1.057808   4.67  13.04
1975-07-13  2.128800   8.79  16.00  ...   5.465714  1.205693   6.67  10.71
1975-07-20  3.164615   2.92  15.87  ...   6.267143  2.873312   5.33  16.21
1975-07-27  5.142732   5.21  20.04  ...   8.500000  3.903720  11.54  20.83
1975-08-03  3.344253   5.54  21.42  ...   4.067143  2.579262   3.71  17.62
1975-08-10  5.212406   5.25  11.79  ...   6.702857  3.875804   6.54  20.12
1975-08-17  1.440040   4.67  10.13  ...   4.065714  2.354611   4.79  12.08
1975-08-24  3.017888   5.46  13.92  ...   7.262857  2.422050   9.00  16.04
1975-08-31  2.810502   3.33  16.62  ...   4.631429  3.457453   7.00  12.71
1975-09-07  1.908479   5.29   9.17  ...   3.984286  1.845507   7.54  15.37
1975-09-14  2.835366   9.42  16.46  ...   7.821429  2.919277   8.92  18.12
1975-09-21  4.575740   7.17  14.50  ...   7.191429  2.917124   8.58  19.58
1975-09-28  5.168922   8.75  19.67  ...  11.500000  4.322866   7.25  28.79
1975-10-05  2.214835  11.17  17.83  ...  10.257143  3.301109   7.71  26.71
1975-10-12  3.174465   3.75  14.17  ...   2.334286  1.507590   5.17  11.21
1975-10-19  5.718251   5.91  16.50  ...   6.601429  3.596778   4.46  22.79
1975-10-26  3.657752  12.42  24.41  ...  14.257143  2.829992  19.17  26.71
1975-11-02  3.239644   9.71  17.21  ...   9.150000  2.442103  11.21  22.88
1975-11-09  4.075657   6.87  16.13  ...   5.827143  3.732009   5.88  20.08
1975-11-16  5.167426   8.00  23.38  ...   6.755714  4.243606   4.21  22.25
1975-11-23  6.368993   1.50  23.16  ...   8.131429  4.665613   3.67  18.96
1975-11-30  4.791123   4.83  16.46  ...   8.125714  3.170178   7.67  20.17
1975-12-07  7.963424   5.96  20.67  ...   8.400000  4.480461   5.58  26.38
1975-12-14  5.213460   3.08  18.50  ...   3.965714  2.462525   4.58  19.00
1975-12-21  4.761010   3.92  24.41  ...   4.894286  2.595514   4.08  16.88
1975-12-28  3.156532   6.96  14.37  ...  10.864286  2.392285  13.70  20.38

                                   MAL
                 mean       std    min    max       mean       std
Yr_Mo_Dy
1975-01-05  15.052000  5.650630  11.63  30.88  22.036000  6.995158
1975-01-12  20.184286  5.409143  13.29  27.42  20.041429  4.740743
1975-01-19  17.114286  7.139386   9.17  28.71  18.362857  7.849195
1975-01-26  23.338571  7.431833  19.95  34.54  26.075714  5.973195
1975-02-02  19.915714  4.763087  11.08  28.58  20.115714  5.963642
1975-02-09  11.887143  3.900725   9.04  17.33  13.078571  3.445356
1975-02-16  10.744286  5.139179   6.54  23.16  11.414286  5.913152
1975-02-23  13.607143  6.689165   6.58  23.42  16.405714  6.788239
1975-03-02  12.160000  2.578210   9.54  19.87  13.874286  3.913020
1975-03-09  12.831429  5.314177   5.41  22.37  14.418571  6.059858
1975-03-16   8.871429  5.323650   8.63  21.75  15.001429  5.365316
1975-03-23  10.210000  3.074519  11.67  22.34  15.721429  3.956684
1975-03-30  14.037143  3.115743  10.58  22.95  17.900000  4.219522
1975-04-06  12.752857  3.102632  11.92  25.62  17.220000  4.523575
1975-04-13  15.464286  4.115268  12.42  33.04  21.000000  8.041849
1975-04-20  14.240000  3.979577   6.71  18.50  11.678571  3.634315
1975-04-27   6.845714  2.019413   2.29  13.42   8.494286  3.885447
1975-05-04  12.495714  6.528333   3.79  23.25  15.445714  7.537356
1975-05-11  11.968571  2.694862   6.29  20.46  12.385714  5.576289
1975-05-18   9.695714  3.862999   5.58  14.79   9.355714  3.795773
1975-05-25  12.571429  2.697050  10.00  18.88  14.787143  3.286993
1975-06-01  12.678571  3.042715   4.33  18.34  10.392857  4.948251
1975-06-08  14.045714  5.570173   9.04  32.79  16.225714  8.563465
1975-06-15   9.250000  2.998300   5.91  17.88  11.272857  4.381399
1975-06-22  11.612857  6.670661   8.63  20.46  13.615714  4.866432
1975-06-29   8.184286  2.917395   7.25  14.96  10.214286  2.596253
1975-07-06   8.118571  3.323013   5.63  11.46   8.078571  2.202366
1975-07-13   8.490000  1.402094   7.96  16.58  10.970000  2.993382
1975-07-20  11.530000  3.908098   4.67  16.08  10.124286  4.743939
1975-07-27  15.727143  2.890592  11.08  22.46  16.447143  4.076795
1975-08-03   7.601429  5.487985   5.21  15.46  10.417143  4.077801
1975-08-10  11.342857  6.038746   6.00  17.79  12.368571  4.564688
1975-08-17   8.238571  2.535346   4.00  12.38   7.965714  2.611895
1975-08-24  11.905714  2.836658  11.08  19.75  15.137143  3.262104
1975-08-31   9.731429  2.450187   4.75  17.41  11.514286  4.511404
1975-09-07  11.207143  2.915977   7.79  17.12  12.071429  3.355614
1975-09-14  13.958571  3.276713  12.12  25.46  17.880000  4.169229
1975-09-21  14.032857  4.667811  13.08  25.58  17.137143  4.394025
1975-09-28  17.184286  7.710214  14.83  30.54  21.485714  6.105186
1975-10-05  15.830000  7.090907  13.46  29.08  21.124286  5.646772
1975-10-12   7.934286  2.491658   5.54  12.54   8.965714  2.636664
1975-10-19  11.905714  6.017194   5.58  24.41  13.195714  5.921325
1975-10-26  22.792857  2.642093  19.75  32.46  25.292857  4.224270
1975-11-02  14.912857  4.409825  12.71  21.62  17.231429  3.443368
1975-11-09  11.112857  5.967858   8.25  22.46  14.715714  5.642930
1975-11-16   8.892857  6.408020   9.75  36.08  15.887143  9.185034
1975-11-23  12.430000  6.146823   8.12  29.63  17.445714  7.814262
1975-11-30  13.042857  4.708017  16.25  28.42  19.735714  4.235748
1975-12-07  12.685714  7.191993  12.33  36.08  21.118571  7.422168
1975-12-14   8.541429  5.499028   8.79  24.83  15.124286  5.062074
1975-12-21   8.870000  4.413287  12.21  20.04  15.712857  2.854118
1975-12-28  16.332857  2.755272  19.17  23.00  21.101429  1.290987

[52 rows x 48 columns]